"""splent_feature_profile

Revision ID: 1c20b908bdae
Revises: 29f0c82ca134
Create Date: 2026-03-21 18:54:00.631520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c20b908bdae'
down_revision = '29f0c82ca134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
