"""splent_feature_profile

Revision ID: a1004987c343
Revises: c1bdef453cc4
Create Date: 2026-03-21 23:56:23.914807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1004987c343'
down_revision = 'c1bdef453cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
