"""splent_feature_profile

Revision ID: c1bdef453cc4
Revises: 1c20b908bdae
Create Date: 2026-03-21 23:53:13.199592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bdef453cc4'
down_revision = '1c20b908bdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
