"""splent_feature_profile

Revision ID: f0861009f5e9
Revises: a1004987c343
Create Date: 2026-03-22 23:10:23.318495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0861009f5e9'
down_revision = 'a1004987c343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
